### PR TITLE
Removes unused partials under `/_includes/`.

### PR DESCRIPTION
**Pull request by jbnicolai**
These seem to have been introduced in e4571d5 "Added content from bastichelaar.github.io", but aren't used in the current project.

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
@bastichelaar did you want to do something with `clients.html`?

**Comment by bastichelaar** [comment]
Well, I'd like to add a row with logo's of customers we're working with. So maybe we could use clients.html for that? :)

**Comment by simonvanderveldt** [comment]
Can we already communicate those?
We can also just remove the file now and re-add it later?

**Comment by bastichelaar** [comment]
Sure, go ahead and merge the pull request :) We'll add the clients section
later!

**Pull request merged**
